IAMURL: https://eu.iam.checkmarx.net
Cx1URL: https://eu.ast.checkmarx.net
Tenant: your_tenant_here
#ProxyURL: http://127.0.0.1:8080
#LogLevel: TRACE
Tests:
  - Name: create project query override and run a scan (old api)
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        Scope: 
          Tenant: false
          Project: e2e-test-query-old-project%E2E_RUN_SUFFIX%
        Source: "result = All.NewCxList();"
        Severity: LOW
        FeatureFlags: [ "QUERY_EDITOR_SAST_BACKWARD_API_ENABLED" ]
        Compile: true   
        OldAPI: true     
        DeleteAuditSession: true
        Test: C
        OnFail:
          FailTestSet: true
    Scans:
      - Project: e2e-test-query-old-project%E2E_RUN_SUFFIX%
        ZipFile: ../files/xss-burger.zip
        Branch: zip
        Preset: e2e-test-query-old-preset%E2E_RUN_SUFFIX%
        Engine: sast
        FeatureFlags: [ "QUERY_EDITOR_SAST_BACKWARD_API_ENABLED" ]
        WaitForEnd: true
        CancelOnTimeout: true
        Timeout: 300 #300 seconds, 5min => scan should take ~1 minute
        Test: C
    Results:
      - Project: e2e-test-query-old-project%E2E_RUN_SUFFIX%
        Type: SAST
        SASTFilter:
          Query: Client_DOM_XSS
          Severity: HIGH
        Test: R
        FeatureFlags: [ "QUERY_EDITOR_SAST_BACKWARD_API_ENABLED" ]
        FailTest: true
  - Name: delete project query override
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        FeatureFlags: [ "QUERY_EDITOR_SAST_BACKWARD_API_ENABLED" ]
        Scope: 
          Tenant: false
          Project: e2e-test-query-old-project%E2E_RUN_SUFFIX%
        Test: D
        OldAPI: true
