version: 2

project_name: cx1e2e

builds:
  - id: default
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    binary: cx1e2e
  - id: static
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: cx1e2e-static
    env:
      - CGO_ENABLED=0

archives:
  - id: zips-default
    formats: zip    
    ids: [default]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: bins-default
    ids: [default]
    formats: binary
    name_template: "{{ .Binary }}"
  - id: zips-static
    formats: zip    
    ids: [static]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_static"
  - id: bins-static
    ids: [static]
    formats: binary
    name_template: "{{ .Binary }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: cxpsemea
    name: cx1e2e