version: 2

project_name: cx1e2e


checks:
  validate-archives: false

builds:
  - id: default
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    binary: cx1e2e
  - id: static
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: cx1e2e-static
    env:
      - CGO_ENABLED=0

archives:
  - formats: zip
    id: zips
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: bins
    formats: binary
    name_template: "{{ .Binary }}"


checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: cxpsemea
    name: cx1e2e