IAMURL: https://eu.iam.checkmarx.net
Cx1URL: https://eu.ast.checkmarx.net
Tenant: your_tenant_here
#ProxyURL: http://127.0.0.1:8080
#LogLevel: TRACE
Tests:
  - Name: create app-level override and run a scan
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        FeatureFlags: [ "AUDIT_APPLICATION_LEVEL_ENABLED" ]
        Scope: 
          Tenant: false
          Application: e2e-query-app%E2E_RUN_SUFFIX%
          Project: e2e-query-project%E2E_RUN_SUFFIX% #Project is still required since the web-audit session is opened in a project's context
        Source: "result = All.NewCxList(); // application override"
        Severity: LOW
        Compile: true
        Test: C
        OnFail:
          FailTestSet: true
    Scans:
      - Project: e2e-query-project%E2E_RUN_SUFFIX%
        ZipFile: ../files/xss-burger.zip
        Branch: zip
        Preset: e2e-query-preset%E2E_RUN_SUFFIX%
        FeatureFlags: [ "AUDIT_APPLICATION_LEVEL_ENABLED" ]
        Engine: sast
        WaitForEnd: true
        CancelOnTimeout: true
        Timeout: 300 #300 seconds, 5min => scan should take ~1 minute
        Test: C
    Results:
      - Project: e2e-query-project%E2E_RUN_SUFFIX%
        FeatureFlags: [ "AUDIT_APPLICATION_LEVEL_ENABLED" ]
        Type: SAST
        SASTFilter:
          Query: Client_DOM_XSS
          Severity: HIGH
        Test: R
        FailTest: true
  - Name: Delete app-level override
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        FeatureFlags: [ "AUDIT_APPLICATION_LEVEL_ENABLED" ]
        Scope: 
          Tenant: false
          Application: e2e-query-app%E2E_RUN_SUFFIX%
          Project: e2e-query-project%E2E_RUN_SUFFIX%
        Test: D        
        DeleteAuditSession: true