IAMURL: https://eu.iam.checkmarx.net
Cx1URL: https://eu.ast.checkmarx.net
Tenant: your_tenant_here
#ProxyURL: http://127.0.0.1:8080
#LogLevel: TRACE
Tests:
  - Name: create project query override and run a scan
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        Scope: 
          Tenant: false
          Project: e2e-query-project%E2E_RUN_SUFFIX%
        Source: "result = All.NewCxList(); //project override"
        Severity: LOW
        Compile: true        
        Test: C
        OnFail:
          FailTestSet: true
    Scans:
      - Project: e2e-query-project%E2E_RUN_SUFFIX%
        ZipFile: ../files/xss-burger.zip
        Branch: zip
        Preset: e2e-query-preset%E2E_RUN_SUFFIX%
        Engine: sast
        WaitForEnd: true
        CancelOnTimeout: true
        Timeout: 300 #300 seconds, 5min => scan should take ~1 minute
        Test: C
    Results:
      - Project: e2e-query-project%E2E_RUN_SUFFIX%
        Type: SAST
        SASTFilter:
          Query: Client_DOM_XSS
          Severity: HIGH
        Test: R
        FailTest: true
  - Name: delete project query override
    Queries:
      - Name: Client_DOM_XSS
        Group: JavaScript_High_Risk
        Language: JavaScript
        Scope: 
          Tenant: false
          Project: e2e-query-project%E2E_RUN_SUFFIX%
        Test: D
        DeleteAuditSession: true
